import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
df_Australia=pd.read_csv('Australia.csv')
df_Australia=df_Australia.drop('Unnamed: 0',axis=1)
df_Australia['PCT filing date '] = pd.to_datetime(df_Australia['PCT filing date '], errors='coerce')
df_Australia = df_Australia.dropna(subset=['PCT filing date '])
df_Australia['PCT filing date '] = df_Australia['PCT filing date '].dt.strftime('%d-%m-%Y')
df_Australia.columns
df_Australia.index=range(89)
df_Australia['Country/Research Organization/Company'].unique()
a=np.where((df_Australia['Country/Research Organization/Company']=='Research Organisation') | (df_Australia['Country/Research Organization/Company']=='Research organisation') |(df_Australia['Country/Research Organization/Company']==' Research organisation'))
df_Australia_University=df_Australia['Owners'].iloc[a]
df_Australia_University=df_Australia_University.to_frame()
df_Australia_University.index=range(10)
df_Australia_University['Organizations']=df_Australia_University['Organizations'].str.strip()
df_Australia_University=df_Australia_University['Owners'].str.split(';',expand=True)
df_Australia_University['Owners'] = df_Australia_University.index
stacked = df_Australia_University.set_index('Owners').stack()
df_Australia_University=stacked.to_frame()
df_Australia_University = stacked.reset_index(name='Organizations')
df_Australia_University_count=df_Australia_University['Organizations'].value_counts()
df_Australia_University=df_Australia_University.drop('Owners',axis=1)
df_Australia_University=df_Australia_University.drop('level_1',axis=1)
df_Australia_University_count=df_Australia_University['Organizations'].value_counts()
df_Australia_University['Organizations']=df_Australia_University['Organizations'].str.upper()
fig,ax=plt.subplots(figsize=(10,5))
df_Australia_University_count.iloc[0:10].plot(kind='barh',color='blue')
plt.ylabel('Name of Organizations')
plt.xlabel('Number of Patents of Top Performing Organizations')
plt.title('Performance of Organizations in Australia')
df_Australia_University.to_csv('Australia_University.csv',sep=',')
df_Australia_University=pd.read_csv('Australia_University.csv')
df_Australia_University=df_Australia_University.drop('Unnamed: 0',axis=1)

df_China=pd.read_csv('China.csv')
df_China=df_China.drop('Unnamed: 0',axis=1)
df_China=df_China.rename({'Unnamed: 6':'Company/ResearchOrganization/Individual'},axis=1)
df_China['Company/ResearchOrganization/Individual'].unique()
a=np.where((df_China['Company/ResearchOrganization/Individual']==' Research organisation') | (df_China['Company/ResearchOrganization/Individual']=='Research organisation, Company') | (df_China['Company/ResearchOrganization/Individual']=='Research organisation') | (df_China['Company/ResearchOrganization/Individual']=='Research Organisation') 
| (df_China['Company/ResearchOrganization/Individual']=='Research Organisation, Individual') | (df_China['Company/ResearchOrganization/Individual']=='Research organization') | (df_China['Company/ResearchOrganization/Individual']=='Company;Research Organization') | (df_China['Company/ResearchOrganization/Individual']=='Research organizations')
| (df_China['Company/ResearchOrganization/Individual']=='Research Organization') | (df_China['Company/ResearchOrganization/Individual']=='Research organization;Company') | (df_China['Company/ResearchOrganization/Individual']=='Reaearch organization') | (df_China['Company/ResearchOrganization/Individual']=='research organization') | (df_China['Company/ResearchOrganization/Individual']=='Research organzation')
| (df_China['Company/ResearchOrganization/Individual']=='Research organiation') | (df_China['Company/ResearchOrganization/Individual']=='university') | (df_China['Company/ResearchOrganization/Individual']=='Hospital') | (df_China['Company/ResearchOrganization/Individual']=='institute and company') | (df_China['Company/ResearchOrganization/Individual']=='LAB') | (df_China['Company/ResearchOrganization/Individual']=='Reasearch Institute')
| (df_China['Company/ResearchOrganization/Individual']=='Research organization; company') | (df_China['Company/ResearchOrganization/Individual']=='University') | (df_China['Company/ResearchOrganization/Individual']=='Researh organization') | (df_China['Company/ResearchOrganization/Individual']=='Company;Research organization') | (df_China['Company/ResearchOrganization/Individual']=='Research organization;company') | (df_China['Company/ResearchOrganization/Individual']=='Institute')
| (df_China['Company/ResearchOrganization/Individual']=='Organisation ') | (df_China['Company/ResearchOrganization/Individual']=='Research institute') | (df_China['Company/ResearchOrganization/Individual']=='Research Organiation'))

df_China_University=df_China['Owners'].iloc[a]
df_China_University=df_China_University.to_frame()
df_China_University['Owners']=df_China_University['Owners'].str.strip()
df_China_University['Owners']=df_China_University['Owners'].str.upper()
df_China_University=df_China_University['Owners'].str.split(';',expand=True)
df_China_University['Owners'] = df_China_University.index
stacked = df_China_University.set_index('Owners').stack()
df_China_University=stacked.to_frame()
df_China_University = stacked.reset_index(name='Organizations')
df_China_University_count=df_China_University['Organizations'].value_counts()
df_China_University=df_China_University.drop('Owners',axis=1)
df_China_University=df_China_University.drop('level_1',axis=1)
df_China_University.index=range(1374)
df_China_University_count=df_China_University['Owners'].value_counts()
fig,ax=plt.subplots(figsize=(10,5))
df_China_University_count.iloc[0:10].plot(kind='barh',color='blue')
plt.ylabel('Name of Organizations')
plt.xlabel('Number of Patents of Top Performing Organizations')
plt.title('Performance of Organizations in China')


df_Canada=pd.read_csv('Canada.csv')
df_Canada['PCT filing date '] = pd.to_datetime(df_Canada['PCT filing date '], errors='coerce')
df_Canada = df_Canada.dropna(subset=['PCT filing date '])
df_Canada['PCT filing date '] = df_Canada['PCT filing date '].dt.strftime('%d-%m-%Y')
df_Canada.columns
df_Canada['Individual/ResearchOrganization/Company'].unique()
a=np.where((df_Canada['Individual/ResearchOrganization/Company']=='Research Organisation') | (df_Canada['Individual/ResearchOrganization/Company']=='RESEARCH ORGANIZATION') | (df_Canada['Individual/ResearchOrganization/Company']=='RESEARCH  ORGANIZATION'))
df_Canada_University=df_Canada['Owners'].iloc[a]
df_Canada_University=df_Canada_University.to_frame()
df_Canada_University.index=range(42)
df_Canada_University['Owners']=df_Canada_University['Owners'].str.upper()
df_Canada_University['Owners']=df_Canada_University['Owners'].str.strip()
df_Canada_University=df_Canada_University.drop([14])
df_Canada_University['Owners'].iloc[9]='HIROSHIMA UNIVERSITY'
df_Canada_University_count=df_Canada_University['Owners'].value_counts()
fig,ax=plt.subplots(figsize=(10,5))
df_Canada_University_count.iloc[0:10].plot(kind='barh',color='blue')
plt.ylabel('Name of Organizations')
plt.xlabel('Number of Patents of Top Performing Organizations')
plt.title('Performance of Organizations in Canada')
df_Canada_University.to_csv('Canada_University.csv',sep=',')


df_Europe=pd.read_csv('Europe.csv')
df_Europe=df_Europe.drop('Unnamed: 0',axis=1)
df_Europe=df_Europe.drop([33,37,51,54,56])
df_Europe.index=range(85)
df_Europe.columns
df_Europe['Individual/ResearchOrganization/Company'].unique()
a=np.where((df_Europe['Individual/ResearchOrganization/Company']=='Research Organisation') | (df_Europe['Individual/ResearchOrganization/Company']=='Research organisation'))
df_Europe_University=df_Europe['Owners'].iloc[a]
df_Europe_University['Owners']=df_Europe_University['Owners'].str.strip()
df_Europe_University['Owners']=df_Europe_University['Owners'].str.upper()
df_Europe_University=df_Europe_University.to_frame()
df_Europe_University_count=df_Europe_University['Owners'].value_counts()
fig,ax=plt.subplots(figsize=(10,5))
df_Europe_University_count.plot(kind='barh',color='blue')
plt.ylabel('Name of Organizations')
plt.xlabel('Number of Patents of Top Performing Organizations')
plt.title('Performance of Organizations in Europe')
df_Europe=df_Europe.drop([29,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49])
df_Europe.to_csv('Europe.csv',sep=',')
df_Europe_University.to_csv('Europe_University.csv',sep=',')


df_Germany=pd.read_csv('Germany.csv')
df_Germany=df_Germany.drop('Unnamed: 0',axis=1)
df_Germany['PCT filing date '] = pd.to_datetime(df_Germany['PCT filing date '], errors='coerce')
df_Germany = df_Germany.dropna(subset=['PCT filing date '])
df_Germany['PCT filing date '] = df_Germany['PCT filing date '].dt.strftime('%d-%m-%Y')
df_Germany.columns
df_Germany['Individual/ResearchOrganization/Company'].unique()
a=np.where((df_Germany['Individual/ResearchOrganization/Company']=='Research Organisation') | (df_Germany['Individual/ResearchOrganization/Company']=='Company,Research Organisation') | (df_Germany['Individual/ResearchOrganization/Company']=='Research Organisation,Company') | (df_Germany['Individual/ResearchOrganization/Company']=='Research organisation') | (df_Germany['Individual/ResearchOrganization/Company']=='Research organization') | (df_Germany['Individual/ResearchOrganization/Company']=='Company; Research Organisation') | (df_Germany['Individual/ResearchOrganization/Company']=='Research Institute'))
df_Germany_University=df_Germany['Owners'].iloc[a]
df_Germany_University=df_Germany_University.to_frame()
df_Germany_University.index=range(45)
df_Germany_University_count=df_Germany_University['Owners'].value_counts()
df_Germany_University['Owners']=df_Germany_University['Owners'].str.upper()
df_Germany_University['Owners']=df_Germany_University['Owners'].str.strip()
fig,ax=plt.subplots(figsize=(10,5))
df_Germany_University_count.iloc[0:10].plot(kind='barh',color='blue')
plt.ylabel('Name of Organizations')
plt.xlabel('Number of Patents of Top Performing Organizations')
plt.title('Performance of Organizations in Germany')
df_Germany.to_csv('Germany.csv',sep=',')
df_Germany_University.to_csv('Germany_University.csv',sep=',')


df_India=pd.read_csv('India.csv')
df_India=df_India.drop('Unnamed: 0',axis=1)
df_India['PCT filing date '] = pd.to_datetime(df_India['PCT filing date '], errors='coerce')
df_India = df_India.dropna(subset=['PCT filing date '])
df_India['PCT filing date '] = df_India['PCT filing date '].dt.strftime('%d-%m-%Y')
df_India.columns
df_India['Company/ResaerchOrganization/Individual'].unique()
a=np.where((df_India['Company/ResaerchOrganization/Individual']=='Research organization') | (df_India['Company/ResaerchOrganization/Individual']=='Research institute') | (df_India['Company/ResaerchOrganization/Individual']=='Research Organization') | (df_India['Company/ResaerchOrganization/Individual']=='Research organization ') | (df_India['Company/ResaerchOrganization/Individual']=='Company, Reseach Organization '))
df_India_University=df_India['Owners'].iloc[a]
df_India_University=df_India_University.to_frame()
df_India_University['Owners']=df_India_University['Owners'].str.strip()
df_India_University['Owners']=df_India_University['Owners'].str.upper()
df_India_University['Owners'].index=range(54)
df_India_University=df_India_University.drop([110,119])
df_India_University_count=df_India_University['Owners'].value_counts()
fig,ax=plt.subplots(figsize=(10,5))
df_India_University_count.iloc[0:10].plot(kind='barh',color='blue')
plt.ylabel('Name of Organizations')
plt.xlabel('Number of Patents of Top Performing Organizations')
plt.title('Performance of Organizations in India')
df_India.to_csv('India.csv',sep=',')
df_India_University.to_csv('India_University.csv',sep=',')


df_Japan=pd.read_csv('Japan.csv')
df_Japan=df_Japan.drop('Unnamed: 0',axis=1)
df_Japan['PCT filing date '] = pd.to_datetime(df_Japan['PCT filing date '], errors='coerce')
df_Japan = df_Japan.dropna(subset=['PCT filing date '])
df_Japan['PCT filing date '] = df_Japan['PCT filing date '].dt.strftime('%d-%m-%Y')
df_Japan.columns
df_Japan['Individual/ResearchOrganization/Company'].unique()
a=np.where((df_Japan['Individual/ResearchOrganization/Company']=='Research Organisation') | (df_Japan['Individual/ResearchOrganization/Company']=='Research organisation') | (df_Japan['Individual/ResearchOrganization/Company']=='Research oganisation'))
df_Japan_University=df_Japan['Owners'].iloc[a]
df_Japan_University=df_Japan_University.to_frame()
df_Japan_University['Owners']=df_Japan_University['Owners'].str.upper()
df_Japan_University['organizations']=df_Japan_University['organizations'].str.strip()
df_Japan_University=df_Japan_University['Organizations'].str.split(',',expand=True)
df_Japan_University['Organizations'] = df_Japan_University.index
stacked = df_Japan_University.set_index('Organizations').stack()
df_Japan_University=stacked.to_frame()
df_Japan_University = stacked.reset_index(name='organizations')
df_Japan_University_count=df_Japan_University['organizations'].value_counts()
df_Japan_University=df_Japan_University.drop('Organizations',axis=1)
df_Japan_University=df_Japan_University.drop('level_1',axis=1)
fig,ax=plt.subplots(figsize=(10,5))
df_Japan_University_count.iloc[0:10].plot(kind='barh',color='blue')
plt.ylabel('Name of Organizations')
plt.xlabel('Number of Patents of Top Performing Organizations')
plt.title('Performance of Organizations in Japan')
df_Japan.to_csv('Japan.csv',sep=',')
df_Japan_University.to_csv('Japan_University.csv',sep=',')


df_SouthKorea=pd.read_csv('SouthKorea.csv')
df_SouthKorea=df_SouthKorea.drop('Unnamed: 0',axis=1)
df_SouthKorea['PCT filing date '] = pd.to_datetime(df_SouthKorea['PCT filing date '], errors='coerce')
df_SouthKorea = df_SouthKorea.dropna(subset=['PCT filing date '])
df_SouthKorea['PCT filing date '] = df_SouthKorea['PCT filing date '].dt.strftime('%d-%m-%Y')
df_SouthKorea.columns
df_SouthKorea['Individual/ResearchOrganization/Company'].unique()
a=np.where((df_SouthKorea['Individual/ResearchOrganization/Company']=='Research Organisation') | (df_SouthKorea['Individual/ResearchOrganization/Company']=='Research organisation ') | (df_SouthKorea['Individual/ResearchOrganization/Company']=='Research organisation') | (df_SouthKorea['Individual/ResearchOrganization/Company']=='Research organisation and Company')
 | (df_SouthKorea['Individual/ResearchOrganization/Company']=='Resarch Organisation ') | (df_SouthKorea['Individual/ResearchOrganization/Company']=='Research Organization ') | (df_SouthKorea['Individual/ResearchOrganization/Company']=='(GOVERNMENT) Research Organisation') | (df_SouthKorea['Individual/ResearchOrganization/Company']=='Research oragnisation') | (df_SouthKorea['Individual/ResearchOrganization/Company']=='Reseach organization ') | (df_SouthKorea['Individual/ResearchOrganization/Company']=='Research Organization'))

df_SouthKorea_University=df_SouthKorea['Owners'].iloc[a]
df_SouthKorea_University=df_SouthKorea_University.to_frame()
df_SouthKorea_University.index=range(148)
df_SouthKorea_University['Owners']=df_SouthKorea_University['Owners'].str.upper()
df_SouthKorea_University['Owners']=df_SouthKorea_University['Owners'].str.strip()
df_SouthKorea_University_count=df_SouthKorea_University['Owners'].value_counts()
fig,ax=plt.subplots(figsize=(10,5))
df_SouthKorea_University_count.iloc[0:10].plot(kind='barh',color='blue')
plt.ylabel('Name of Organizations')
plt.xlabel('Number of Patents of Top Performing Organizations')
plt.title('Performance of Organizations in SouthKorea')
df_SouthKorea.to_csv('SouthKorea.csv',sep=',')
df_SouthKorea_University.to_csv('SouthKorea_University.csv',sep=',')

df_USA=pd.read_csv('USA.csv')
df_USA=df_USA.drop('Unnamed: 0',axis=1)
df_USA['PCT filing date '] = pd.to_datetime(df_USA['PCT filing date '], errors='coerce')
df_USA = df_USA.dropna(subset=['PCT filing date '])
df_USA['PCT filing date '] = df_USA['PCT filing date '].dt.strftime('%d-%m-%Y')
df_USA.columns
df_USA['Individual/ResearchOrganization/Company'].unique()
a=np.where((df_USA['Individual/ResearchOrganization/Company']=='Research organization') | (df_USA['Individual/ResearchOrganization/Company']=='Research organisation') | (df_USA['Individual/ResearchOrganization/Company']=='Research organistion') | (df_USA['Individual/ResearchOrganization/Company']=='University') | (df_USA['Individual/ResearchOrganization/Company']=='research organisation') | (df_USA['Individual/ResearchOrganization/Company']=='Research organisation; Company')
  | (df_USA['Individual/ResearchOrganization/Company']=='Research Organisation') | (df_USA['Individual/ResearchOrganization/Company']=='Research Organization') | (df_USA['Individual/ResearchOrganization/Company']=='Company And Univ.') | (df_USA['Individual/ResearchOrganization/Company']=='UNIVERSITY'))
df_USA_University=df_USA['Owners'].iloc[a]
df_USA_University=df_USA_University.to_frame()
df_USA_University.index=range(120)
df_USA_University['Owners']=df_USA_University['Owners'].str.upper()
df_USA_University['Owners']=df_USA_University['Owners'].str.strip()
df_USA_University=df_USA_University.drop([0,1,2,3,4,5,7,20])
df_USA_University_count=df_USA_University['Owners'].value_counts()
fig,ax=plt.subplots(figsize=(10,5))
df_USA_University_count.iloc[0:10].plot(kind='barh',color='blue')
plt.ylabel('Name of Organizations')
plt.xlabel('Number of Patents of Top Performing Organizations')
plt.title('Performance of Organizations in USA')
df_USA.to_csv('USA.csv',sep=',')
df_USA_University.to_csv('USA_University.csv',sep=',')
